### ISSUE TITLE
How to get it to send 401 instead of 403

### ISSUE THREAD

**Issue by paulraines68** [mschout/apache-authcookie#4]
Is there way to get AuthCookie to send a 401 status instead of a 403 status.  401 means "I don't know who you are" which is what is generally true if the user has not logged in yet.  403 means "I know who you are but you don't have access" which is the case when the the user is logged in (have valid cookie) but they are not in the valid-user list.

AuthCookie always seems to send 403 no matter what the case.

**Comment by mschout** [comment]
What version of apache are you running?

AuthCookie *does* send 403 responses.  See Apache2/AuthCookie.pm's authorize() handler method for example which returns HTTP_FORBIDDEN (403) if necessary.

**Comment by paulraines68** [comment]
I see in the authorize(handler) you return HTTP_FORBIDDEN unless ($user) exists (i.e. user is undef or =0).  It is my understanding that you should be returning HTTP_UNAUTHORIZED there instead. 

I am running Apache 2.2.15 (the highly backported RedHat one) on CentOS6

**Comment by mschout** [comment]
Hm, yes that does seem correct.  I'll change that. 

Note that this will change *THAT* instance from a 401 to a 403 response.  You seem to have another problem if you are not getting 401 responses.

**Comment by mschout** [comment]
Ok, sorry for the misinformation.  I haven't messed with this code in quite some time.

Your suggest to return HTTP_UNAUTHORIZED instead is only correct if you are using HTTP Basic auth as implemented by the browser.  This is not correct for AuthCookie, which is intended to avoid the browsers built in HTTP Basic auth altogether.

When a 401 response is received from the server, the browser will show its native username/password form and sends the request again using HTTP basic auth headers.  This is mainly what AuthCookie was created back in the 90s to work around.  We do not want HTTP basic auth and we do not want the browser's native username/password dialogs.

The only way to reliably prevent the brower from displaying the basic auth username/password form is to use a different HTTP response code.  Hence 403 Unauthorized was used instead.

As a result, I cannot change the HTTP_FORBIDDEN to HTTP_UNAUTHORIZED in the authorize method.  AuthCookie is already doing the correct thing there in order to avoid triggering HTTP Basic auth in the browser.

If you are looking for a HTTP basic auth implemenation instead of AuthCookie, you will either need to use one of the many implementations available on CPAN (e.g.: Apache::AuthDBI), or, roll your own.

**Comment by paulraines68** [comment]
Ah, I see.  Thanks for the explanation.
